---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-controller
    spec:
      containers:
      - name: job-controller
        image: {{JOB_CONTROLLER_IMAGE}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: svaccount
          mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
        {% set mountpoints=RJC_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        env:
        - name: REANA_STORAGE_BACKEND
          value: {% if DEPLOYMENT == 'prod' %}CEPHFS{% else %}LOCAL{% endif %}
        - name: WDB_SOCKET_SERVER
          value: "wdb"
        - name: WDB_NO_BROWSER_AUTO_OPEN
          value: "True"
        - name: FLASK_DEBUG
          value: "1"
      volumes:
      - name: svaccount
        secret:
          secretName: {{K8S_APISERVER_SECRET}}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
