---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
      - name: message-broker
        image: {{MESSAGE_BROKER_IMAGE}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        {% set mountpoints=RMB_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5672
          name: tcp
        - containerPort: 15672
          name: management
        env:
        - name: WDB_SOCKET_SERVER
          value: "wdb"
        - name: WDB_NO_BROWSER_AUTO_OPEN
          value: "True"
      volumes:
        {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
