---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{SERVER_IMAGE}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        volumeMounts:
        {% set mountpoints=RS_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: WDB_SOCKET_SERVER
          value: "wdb"
        - name: WDB_NO_BROWSER_AUTO_OPEN
          value: "True"
        - name: FLASK_DEBUG
          value: "1"
      volumes:
        {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
