apiVersion: v1
clusters:
- cluster:
    # Since minikube generates self-signed certificate that doesn't include
    # hostname pccda003.cern.ch tls hostname verify has to be skipped
    insecure-skip-tls-verify: true
    #certificate-authority: /home/hahirvon/.minikube/ca.crt
    server: https://pccda003.cern.ch:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXBxa3E3Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJjMzhlOWQ3Zi1mYTE1LTExZTctYjAzMC0wODAwMjc3ZmRmYzUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.GFqCuM-k7xto-jiI-7oikrLYo6mvs36btGL1MK3ut28C7OKBeAQhH_-EbTL8uhi-bt_8SCKlz7lbiupOXB1jaWCMT112qjSTygDe6L5Yc3wzEp8kQ1uHAyhyxQo_ngR4fV_IzarJ2LUSTZSYQRMUfzORIOH_bTYjTFzjdEkQ1yosBixfPlAZ-VmstsGNzlhGmBnf0_9YdSt9GiOW5UXCWG3pPSNwJRLnQrge6fG0sLjSul0qdhfGoLy4-r1hZwHX2YP72GrKSCCU33BhZRu89Ng44uFn8y6lv49pXyXJySGs5br5tAydn__Rff-8zBmcwaqr8YbLzfZbOBCBDV6eog
#    client-certificate: /home/hahirvon/.minikube/client.crt
#    client-key: /home/hahirvon/.minikube/client.key
